### ISSUE TITLE
Counter not showing

### ISSUE THREAD

**Issue by Rc85** [demchenkoalex/react-native-module-template#10]
I cloned the repo, didn't rename or unlink native modules, basically using default settings and did `yarn` in both root and example directory. I changed `main` in root's `package.json` to `src/index.tsx`. Then I run `yarn android` in example folder but my app is just blank white screen. Nothing showing up in console either.

There is no Fash Refresh when editing `App.tsx` in example and `index.tsx` in root's src.

Did I miss a step?

**Comment by demchenkoalex** [comment]
Hi @Rc85 I ran the same stuff you did and also got a blank screen, but quickly realised that this is because I had packager opened for the other project, and then I started packager (`yarn start`) in the example folder and refreshed the app, counter appeared. Could you please verify?

**Comment by Rc85** [comment]
Re-cloned the repo, did everything mentioned, this time including the steps explained in the article about using module resolver. Did `yarn start` and `yarn android` and still white screen. I'm running this on an actual android device. Added another `console.log` in example's `App.tsx`'s `useEffect`, and nothing showing in console.

Weird thing is, making any changes to `App.tsx` and saving does not refreshing the app on my device. Pressing R in the bundler reloads the app. I went ahead and returned `<View><Text>Hi</Text></View>` instead of the counter in `App.tsx`, still white screen.

I'm out of ideas. I read in an article that this library was highly recommended. I decided to us `@react-native-community/bob` yesterday, and it worked right out of the box. Anyways, let me know if you need to me to verify anything else.

**Comment by demchenkoalex** [comment]
Hi @Rc85 glad you have found an alternative! Re-cloned the repo as you did, `yarn` in both folders and `yarn android` on an actual device, everything works, so I can't suggest anything either.. the difference probably in machines we use, like OS, node version, android studio version etc. Anyway, my point with this library was making a minimal working setup for creating a library, and in the readme I am trying to explain how everything works, so it can be easily done manually by the developer :)
