### ISSUE TITLE
I want to add custom fonts to the module

### ISSUE THREAD

**Issue by zumaawad** [demchenkoalex/react-native-module-template#16]
I want to add custom fonts to the module, so how to?

**Comment by demchenkoalex** [comment]
Hi @zumaawad custom fonts need to be linked to native projects, on the app level, not package level. Unless you do some CocoaPods magic for iOS, and I don't know Android at all. So please do your own research, it is much more advanced than adding static elements like images or something. This is a minimal basic template for the RN module, you could build upon it.
