### ISSUE TITLE
Unable to resolve module ./index

### ISSUE THREAD

**Issue by T0mAl3x** [demchenkoalex/react-native-module-template#24]
I'm having trouble in testing the lib in example app.
Steps I made to build the project:
root folder: yarn
example folder: yarn
example folder: npx pod-install
example folder: yarn ios

This is the error shown in simulator:

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module ./index from path_to_project/Work/react-native-cookie-parser/.: <br><br>None of these files exist:<br> &nbsp;* index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)<br> &nbsp;* index/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (path_to_project/Work/react-native-cookie-parser/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (path_to_project/Work/react-native-cookie-parser/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)<br> &nbsp; &nbsp;at path_to_project/Work/react-native-cookie-parser/node_modules/metro/src/lib/transformHelpers.js:129:24<br> &nbsp; &nbsp;at Server._resolveRelativePath (path_to_project/Work/react-native-cookie-parser/node_modules/metro/src/Server.js:1072:12)<br> &nbsp; &nbsp;at async Server.requestProcessor [as _processBundleRequest] (path_to_project/Work/react-native-cookie-parser/node_modules/metro/src/Server.js:428:37)<br> &nbsp; &nbsp;at async Server._processRequest (path_to_project/Work/react-native-cookie-parser/node_modules/metro/src/Server.js:380:9)</pre>
</body>
</html>

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0

**Comment by demchenkoalex** [comment]
Hey @T0mAl3x do you have `index` in the `path_to_project/Work/react-native-cookie-parser/.`? Also check `main` in `package.json` of the library (no the example) does it point to lib or src? check if you have those files

**Comment by T0mAl3x** [comment]
Hello

Apparently there was another metro process that was running in background. I killed it and the example app run correctly. I do not know how that happend (I checked all opened terminals and nothing was running) but now it works.
I will close the issue.

Thank you for your response
